version: "3.9"
services:
  builder:
    restart: "no"
    build: 
      target: ${ENV_TYPE}
      context: ./
      dockerfile: ./Dockerfile.builder
    volumes:
      - "./src:/usr/ui/src"
      - "public-js:/usr/ui/public/js"
  nginx:
    restart: always
    build: 
      context: ./
      dockerfile: ./Dockerfile.nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "./public/css:/www/css"
      - "./public/html:/www/html"
      - "public-js:/www/js"

volumes:
  public-js:
    driver: local
