version: "3.9"
services:
  builder:
    restart: "no"
    build: 
      target: ${ENV_TYPE}
      context: ./
      dockerfile: ./Dockerfile.builder
    volumes:
      - "./src:/usr/ui/src"
      - "./lib:/usr/ui/lib"
      - "./public:/usr/ui/public/"
  nginx:
    restart: always
    build: 
      context: ./
      dockerfile: ./Dockerfile.nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "./public:/www/public"
